global:
  scrape_interval: 15s
scrape_configs:
- job_name: client
  static_configs:
  - targets:
    - client:9100
- job_name: storage
  static_configs:
  - targets:
    - storage1:9100
    - storage2:9100
    - storage3:9100
